NDefines.NGraphics.MINIMUM_PROVINCE_SIZE_IN_PIXELS = 0
NDefines.NGraphics.COUNTRY_FLAG_TEX_MAX_SIZE = 2048
NDefines.NGraphics.COUNTRY_FLAG_MEDIUM_TEX_MAX_SIZE = 1024
NDefines.NGraphics.COUNTRY_FLAG_SMALL_TEX_MAX_SIZE = 512
NDefines.NGraphics.COUNTRY_FLAG_STRIPE_TEX_MAX_WIDTH = 10
NDefines.NGraphics.COUNTRY_FLAG_STRIPE_TEX_MAX_HEIGHT = 8196
NDefines.NGraphics.COUNTRY_FLAG_LARGE_STRIPE_MAX_WIDTH = 41
NDefines.NGraphics.COUNTRY_FLAG_LARGE_STRIPE_MAX_HEIGHT = 24000
NDefines.NDiplomacy.TENSION_STATE_VALUE = 1.4
NDefines.NDiplomacy.TENSION_ANNEX_NO_CLAIM = 1.5
NDefines.NDiplomacy.TENSION_TIME_SCALE_MONTHLY_FACTOR = -0.007

-- Wider zoom range
NDefines.NFrontend.CAMERA_MIN_HEIGHT = 25.0
NDefines.NFrontend.CAMERA_MAX_HEIGHT = 3625.0 